// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Day20SignalRChat.DAL.Entities;

public partial class ChatMessage
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Message { get; set; }

    public DateTime SentAt { get; set; }
}